// This file will be auto-generated by Supabase CLI
// For now, we'll use a basic structure that matches our schema
export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          name: string | null;
          country: string | null;
          main_service: string | null;
          years_experience: number | null;
          created_at: string;
        };
        Insert: {
          id: string;
          email: string;
          name?: string | null;
          country?: string | null;
          main_service?: string | null;
          years_experience?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          name?: string | null;
          country?: string | null;
          main_service?: string | null;
          years_experience?: number | null;
          created_at?: string;
        };
      };
      plans: {
        Row: {
          id: string;
          name: string;
          monthly_price_usd: number;
          setup_fee_usd: number;
          lifetime_price_usd: number;
          stripe_product_id: string | null;
          stripe_price_setup_id: string | null;
          stripe_price_monthly_id: string | null;
          stripe_price_lifetime_id: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          monthly_price_usd: number;
          setup_fee_usd: number;
          lifetime_price_usd: number;
          stripe_product_id?: string | null;
          stripe_price_setup_id?: string | null;
          stripe_price_monthly_id?: string | null;
          stripe_price_lifetime_id?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          monthly_price_usd?: number;
          setup_fee_usd?: number;
          lifetime_price_usd?: number;
          stripe_product_id?: string | null;
          stripe_price_setup_id?: string | null;
          stripe_price_monthly_id?: string | null;
          stripe_price_lifetime_id?: string | null;
        };
      };
      subscriptions: {
        Row: {
          id: string;
          user_id: string;
          plan_id: string;
          status: 'active' | 'canceled' | 'past_due' | 'trialing';
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          renewal_date: string | null;
          is_lifetime: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          plan_id: string;
          status?: 'active' | 'canceled' | 'past_due' | 'trialing';
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          renewal_date?: string | null;
          is_lifetime?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          plan_id?: string;
          status?: 'active' | 'canceled' | 'past_due' | 'trialing';
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          renewal_date?: string | null;
          is_lifetime?: boolean;
          created_at?: string;
        };
      };
      profiles: {
        Row: {
          id: string;
          user_id: string;
          base_hourly_rate: number;
          target_annual_income: number;
          currency: string;
          typical_weekly_hours: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          base_hourly_rate: number;
          target_annual_income: number;
          currency: string;
          typical_weekly_hours: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          base_hourly_rate?: number;
          target_annual_income?: number;
          currency?: string;
          typical_weekly_hours?: number;
          created_at?: string;
        };
      };
      project_types: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          description: string | null;
          complexity: number;
          typical_duration_days: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          description?: string | null;
          complexity: number;
          typical_duration_days: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          description?: string | null;
          complexity?: number;
          typical_duration_days?: number;
          created_at?: string;
        };
      };
      generated_packages: {
        Row: {
          id: string;
          user_id: string;
          project_type_id: string;
          package_name: 'Starter' | 'Standard' | 'Premium';
          price: number;
          short_description: string;
          includes_text: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          project_type_id: string;
          package_name: 'Starter' | 'Standard' | 'Premium';
          price: number;
          short_description: string;
          includes_text: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          project_type_id?: string;
          package_name?: 'Starter' | 'Standard' | 'Premium';
          price?: number;
          short_description?: string;
          includes_text?: string;
          created_at?: string;
        };
      };
    };
  };
};


